- french/website/rules.js
Rules as been updated in French. Thank you.
Alexxkill French Moderator
> French rules by Alexxkill

- french/darkrp/sh_french.lua
> This should be a little better

- all/ldscr/locale.js
are you proud of my git skills noiwex
> better translation for loading screen

- french/darkrp/sh_french.lua
Many mistakes corrected, and better translation.
> Many mistakes corrected.

- french/website/rules.js
An unnecessary dot, and a modified sentence.
> Just a few changes.

- all/ldscr/locale.js
Some modifications, should be better.
> Some modifications

- french/website/rules.js
> little mistake

- french/darkrp/sh_french.lua
> some edits

- french/website/rules.js
> Important error fixed

- french/website/rules.js
Some modifications, it is not urgent to apply it right now. The modifications are just corrections.
> Some modifications.

- french/darkrp/sh_french.lua
> French elections

- french/darkrp/sh_french.lua
> little mistake fixed

- french/website/rules.js
> improvement

- all/nxshop/locale.lua
> french fix

- french/darkrp/sh_french.lua
> Admin tp svp

- french/darkrp/sh_french.lua
> remove a useless word

- french/darkrp/sh_french.lua
disctricts translated into french
> disctricts

- french/website/shop.json
PayPal French Translattion fixing
> PayPal French Translation fixing

- french/website/rules.js
French rules enhancement (typos, syntax)
> French rules enhancement (typos, syntax)

- french/website/shop.json
> topup, balance, list_desc

- french/darkrp/sh_french.lua
Many improvements for french language (synced from new updates)
> Many improvements for french language (synced)

- french/darkrp/sh_french.lua
> Can steal cars

- french/website/rules.js
Rules are now CLEAR for players and moders (curfews, warrants, etc.)
> Rules are now CLEAR for players and moders

- french/darkrp/sh_french.lua
> nouveautés

- french/darkrp/sh_french.lua
> DarkRP translation (printers, props)

- french/website/rules.js
> remove useless thing

- french/website/header.json
Since no one adds it, I'd to add it. It's from Crowdin.
> header.json

- french/website/profile.json
Since no one adds it, I'd to add it. It's from Crowdin.
> profile.json

- french/website/rules.js
> you can merge noivvex

- french/website/rules.js
> enhanced rules - lots of typos fixed

- french/darkrp/sh_french.lua
> ballot + handcuffs spawn

- french/website/rules.js
> removal of Q&A
